name: publish changed files to move-natives on release

on:
  workflow_run:
    workflows: ["Release rust libmovevm"]
    types:
      - completed

jobs:
  copy-files:
    name: Copy files to move-natives
    if: startsWith(github.event.workflow_run.head_branch, 'v') # Check if the run was triggered by a tag, adjust 'v' if needed
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: | 
          echo ${{ github.event.workflow_run.head_commit.id }}
          echo ${{ github.event.workflow_run.name }}
          echo ${{ github.event.workflow_run.head_branch }}
      
      - name: checkout movevm repository
        uses: actions/checkout@v4

      - name: push files to move-natives
        uses: initia-labs/actions/push-to-repo@main
        env:
          TOKEN_GITHUB: ${{ secrets.PUBLISH_TOKEN }}
        with:
          sources: |
            precompile/modules/initia_stdlib
            precompile/modules/minitia_stdlib
            precompile/modules/move_nursery
            precompile/modules/move_stdlib
          destination-username: 'SeUkKim'
          destination-repo: 'move-natives'
          destination-branch: 'main'
          email: 'infra@initia.xyz'
          commit-msg: 'bump movevm on release ${{ github.event.workflow_run.head_commit.message }}'
